services:
  - type: web
    name: motherboard-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: API_TOKEN
        sync: false
      - key: SPREADSHEET_ID
        sync: false